### ISSUE TITLE
Creare pagina wiki con gli strumenti utili

### ISSUE THREAD

**Issue by aborruso** [openamat/Mappe#4]
Una pagina in cui elencare i tools utili/esenziali (qgis, gdal/ogr,spatialite,cURL, ...)

**Comment by pigreco** [comment]
Una pagina per strumento?
per QGIS posso realizzarla io!!!

**Comment by aborruso** [comment]
@pigreco per ora una pagina con la lista degli strumenti essenziali. Cosa serve per apperecchiare la tavola e mangiare queste pietanze?

**Comment by aborruso** [comment]
Pagina creata https://github.com/openamat/Mappe/wiki/Tools-utili-(da-migliorare)
